title: GDG Pisa
description: Sito Ufficiale del GDG Pisa
author: GDG Pisa
logo: /static/img/avatar.png
github: https://github.com/gdgpisa
about: Google Developer Group Pisa

baseurl: "https://gdgpisa.it"
url: "https://gdgpisa.github.io"

allowsearch: true

# disqus_shortname: aboutashu
# google_analytics: UA-72862926-1

share:
  twitter_username: \gdgpisa
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/blog/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist, jekyll-redirect-from]
